### ISSUE TITLE
Incorrect message for <cflocation> addtoken report

### ISSUE THREAD

**Issue by andrew-dixon** [foundeo/fixinator#1]
For the `<cflocation>` addtoken report, if the attribute exists but is set to `yes` or `true` it reports that it is missing, like this:

        [MEDIUM] CFLocation Missing Add Token found on line 357 of handleOption.cfm high confidence
        The CFLocation tag will automatically add the Session Identifiers (CFID, CFTOKEN or JSESSIONID) to the URL which increases risks for session hijacking.
        <cflocation url="/login" addtoken="true">

Whilst not a big issue, I did have to read the issue message a couple of times before I realised what it meant.

**Comment by pfreitag** [comment]
Ok, thanks there was some code to ignore that case - so I'll look into see why it was not working - should be a simple fix / quick turnaround.

**Comment by pfreitag** [comment]
Ah sorry, I read that too quickly -- the messaging needs to be adjusted, but the finding is correct.

**Comment by pfreitag** [comment]
Better messaging added:

```
[MEDIUM] CFLocation Adds Session Token found on line 2 of simple.cfm high confidence
The CFLocation tag will automatically add the Session Identifiers (CFID, CFTOKEN or JSESSIONID) to the URL unless addtoken=false/no which increases risks for session hijacking.
/vulnerable/missing-addtoken/simple.cfm:2
    2: <cflocation url="moo.cfm" addtoken="true">
```
