### ISSUE TITLE
Payload error detail never outputted

### ISSUE THREAD

**Issue by UpUpDwnDwnLftRt** [foundeo/fixinator#11]
In fixinator.cfc lines 385-389 are not outputting to Commandbox shell (v5.6.1+00618).  

```
print.line().boldRedLine("---- Fixinator Client Error ----").line();
print.redLine(err.message);
if (structKeyExists(err, "detail")) {
	print.whiteLine(err.detail);	
}
```

I am using enterprise version installed locally with the latest updated code and when attempting to scan using the root folder of my application's code I kept getting an unhelpful response in Commandbox of "Fixinator Exiting Due to Error" with no other detail.  As far as I can tell the above code should have run to output the detail but for some reason isn't.

As a side note, most of the erroring was due to [https://dev.lucee.org/t/5-3-9-160-underload-causing-java-lang-nullpointerexception/11007](url) which is because of the Lucee version that CommandBox installs (after updating it to the latest snapshot I no longer received that error).  This is likely because it was a large number of files, some of which were somewhat large.

My other errors were due to 408 errors for which I modified FixinatorClient.cfc : line 399 to run through the retry for them and then I no longer get the issue.

**Comment by pfreitag** [comment]
Thanks for the report - I believe these issues have been addressed already, let me know if you are still having issues.
