### ISSUE TITLE
Update GitHub documentation to use actions/checkout@v4

### ISSUE THREAD

**Issue by garciadev** [foundeo/fixinator#15]
I set up the GitHub Fixinator action using the examples specified in the documentation.

https://github.com/foundeo/fixinator/wiki/Running-Fixinator-on-Github-Actions

Those examples use actions/checkout@v2, but now I am getting warnings in the Fixinator scans that it's using Node v16 and we should upgrade to Node v20. Reviewing the GitHub docs, it looks like this is a simple fix, as you can use v4 instead of v2:

`actions/checkout@v4`

Can you update the documentation to reflect that or any other updated settings? Using v4 worked for me, and I no longer see those annotations in my scans.

**Comment by pfreitag** [comment]
updated - thanks!
