### ISSUE TITLE
Allow passing multiple directories in path argument

### ISSUE THREAD

**Issue by michaelborn** [foundeo/fixinator#2]
So, we can do this in fixinator:
```bash
fixinator path=models
```

but we can't pass multiple directories:

```bash
fixinator path=models,handlers
```

I get "Sorry, /var/lib/dir/models,handlers is not a file or directory".

**Comment by pfreitag** [comment]
Thanks @michaelborn - yes it is not supported currently. I'll look into adding support for this.

**Comment by pfreitag** [comment]
Planning on implementing this with CommandBox's File Globber: 

https://github.com/Ortus-Solutions/globber
https://www.youtube.com/watch?v=zuBchLIiXUY

**Comment by michaelborn** [comment]
Thanks Pete!

**Comment by elpete** [comment]
This issue seems fixed in the latest version of Fixinator.

**Comment by pfreitag** [comment]
Yes it is fixed in version 2.0.0 and up
