### ISSUE TITLE
Usage of arrayEach() causes error in Adobe CF 2018 when working directly with FixinatorClient.cfc

### ISSUE THREAD

**Issue by dnslv** [foundeo/fixinator#4]
I'm building a custom client to use Fixinator Service without command box using Adobe CF2018.
It it very simple, I create an instance of FixinatorClient component and then set the API key and call run() method passing an absolute path to a file and config struct.

I got error on line 106 of FixinatorClient.cfc due to the fact that Adobe CF2018 arrayEach() does not support the last two arguments.

`arrayEach(local.batches, processBatch, true, arrayLen(local.batches));`

I did remove the last two arguments and was able to continue.

**Comment by pfreitag** [comment]
Thanks for letting me know - that is used in order to process batches of files in parallel. I will look into it and see if there is a way to work around this but your workaround is a good solution.

**Comment by pfreitag** [comment]
Going to close this issue, it is possible to use arrayEach in CF2021, if you need CF2018 support there best approach is to just edit the file, there isn't a good way to work around it otherwise.
