### ISSUE TITLE
Slow execution when calling cloud service directly from instance of FixinatorClient.cfc

### ISSUE THREAD

**Issue by dnslv** [foundeo/fixinator#5]
When I try to run the code below it takes over 5 min to get response but I get one at the end.

`<cfset FX = new FixinatorClient()>`
`<cfset result = FX.run(path = "SOME-FILE")>`

Poking around found out that the problem is on line 90 of FixinatorClient:

`local.batches = [{batchType:"progressBar", hasProgressBar:hasProgressBar, progressBar:progressBar, lock_name=local.lock_name}];`

When I commented out the line, the execution went down to a few seconds. I would assume that you have some timeout that creates the hold up. You already have hasProgressBar flag, so maybe you can skip the addition of progressBar to the local.batches array.

**Comment by pfreitag** [comment]
Yes, noted - will remove that if hasProgressBar is false in next update.

**Comment by pfreitag** [comment]
This has been fixed.
